# Welcome to Serverless!
#
# This file is the main config file for your service.
# It's very minimal at this point and uses default values.
# You can always add more config options for more control.
# We've included some commented out config examples here.
# Just uncomment any of them to get that config option.
#
# For full config options, check the docs:
#    docs.serverless.com
#
# Happy Coding!

service: tag-backend
# app and org for use with dashboard.serverless.com
app: tag-backend-app
org: andrewshieh7379

# You can pin your service to only deploy with a specific Serverless version
# Check out our docs for more details
frameworkVersion: "2"

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  stage: dev
  region: us-west-2
  environment:
    userTagTable: ${self:custom.userTagTable}
    sensorTable: ${self:custom.sensorTable}
    socketTable: ${self:custom.socketTable}
    region: us-west-2
    imageUploadBucket: ${self:custom.imageUploadBucket}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:*
        - s3:*
      Resource: "*"

plugins:
  - serverless-webpack

package:
  individually: true

custom:
  userTagTable: user-tag
  sensorTable: sensor-reading
  socketTable: websocket-connection
  imageUploadBucket: tag-image-upload-bucket
  webpack:
    packager: npm

functions:
  getUserPet:
    handler: lambdas/functions/getUserPet.handler
    events:
      - http:
          path: users/{username}/tags/{petName}
          method: GET
          cors: true
          # authorizer:
          #   name: CognitoAuth
          #   type: COGNITO_USER_POOLS
          #   arn:
          #     Fn::GetAtt:
          #       - CognitoUserPool
          #       - Arn

  getUserPetAll:
    handler: lambdas/functions/getUserPet.handler
    events:
      - http:
          path: users/{username}/tags/
          method: GET
          cors: true
          # authorizer:
          #   name: CognitoAuth
          #   type: COGNITO_USER_POOLS
          #   arn:
          #     Fn::GetAtt:
          #       - CognitoUserPool
          #       - Arn

  createTag:
    handler: lambdas/functions/createTag.handler
    events:
      - http:
          path: users/{username}/tags
          method: POST
          cors: true
          request:
            parameters:
              paths:
                username: true
          # authorizer:
          #   name: CognitoAuth
          #   type: COGNITO_USER_POOLS
          #   arn:
          #     Fn::GetAtt:
          #       - CognitoUserPool
          #       - Arn

  getSensorData:
    handler: lambdas/functions/getSensorData.handler
    events:
      - http:
          path: tags/{tagId}/sensors
          method: GET
          cors: true
          request:
            parameters:
              paths:
                tagId: true
              querystrings:
                t: false
          # authorizer:
          #   name: CognitoAuth
          #   type: COGNITO_USER_POOLS
          #   arn:
          #     Fn::GetAtt:
          #       - CognitoUserPool
          #       - Arn

  createUser:
    handler: lambdas/functions/createUser.handler
    events:
      - cognitoUserPool:
          pool: ${self:provider.stage}-tag-user-pool
          trigger: PostConfirmation
          existing: true

  petImageUpload:
    handler: lambdas/functions/petImageUpload.handler
    events:
      - http:
          path: pet-img
          method: POST
          cors: true

  # Websocket functions
  onConnect:
    handler: lambdas/websockets/onConnect.handler
    events:
      - websocket:
          route: $connect

  onDisconnect:
    handler: lambdas/websockets/onDisconnect.handler
    events:
      - websocket:
          route: $disconnect

  handleSensorUpdate:
    handler: lambdas/websockets/handleSensorUpdate.handler
    events:
      - stream:
          type: dynamodb
          arn:
            Fn::GetAtt: [sensorReadingTable, StreamArn]

# you can add CloudFormation resource templates here
resources:
  Resources:
    userTagTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.userTagTable}
        AttributeDefinitions:
          - AttributeName: PK
            AttributeType: S
          - AttributeName: SK
            AttributeType: S
        KeySchema:
          - AttributeName: PK
            KeyType: HASH
          - AttributeName: SK
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 2
          WriteCapacityUnits: 2

    sensorReadingTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.sensorTable}
        AttributeDefinitions:
          - AttributeName: PK
            AttributeType: S
          - AttributeName: SK
            AttributeType: N
        KeySchema:
          - AttributeName: PK
            KeyType: HASH
          - AttributeName: SK
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 2
          WriteCapacityUnits: 2
        StreamSpecification:
          StreamViewType: KEYS_ONLY

    SocketTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.socketTable}
        AttributeDefinitions:
          - AttributeName: ConnectionId
            AttributeType: S
          - AttributeName: TagId
            AttributeType: S
        KeySchema:
          - AttributeName: ConnectionId
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 2
          WriteCapacityUnits: 2
        GlobalSecondaryIndexes:
          - IndexName: TagIdIndex
            KeySchema:
              - AttributeName: TagId
                KeyType: HASH
            Projection:
              ProjectionType: ALL
            ProvisionedThroughput:
              ReadCapacityUnits: 2
              WriteCapacityUnits: 2

    TagUserPool:
      Type: AWS::Cognito::UserPool
      Properties:
        UserPoolName: ${self:provider.stage}-tag-user-pool
        AutoVerifiedAttributes:
          - email
        AliasAttributes:
          - email
        Schema:
          - Name: given_name
            AttributeDataType: String
            Mutable: true
            Required: true
          - Name: family_name
            AttributeDataType: String
            Mutable: true
            Required: true
          - Name: email
            AttributeDataType: String
            Mutable: true
            Required: true

    TagUserPoolClient:
      Type: AWS::Cognito::UserPoolClient
      Properties:
        ClientName: ${self:provider.stage}-tag-user-pool-client
        UserPoolId:
          Ref: TagUserPool
        GenerateSecret: false
        ExplicitAuthFlows:
          - ALLOW_USER_SRP_AUTH
          - ALLOW_REFRESH_TOKEN_AUTH

    ImageUploadBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:custom.imageUploadBucket}
        AccessControl: PublicRead
